### ISSUE TITLE
JavaScript error when visiting /list/

### ISSUE THREAD

**Issue by jelly** [der-michik/c3bottles#52]
I've run npm build but still this error pops up. I could only figure out that the require() causes i.t

```
require("datatables-bootstrap3-plugin");
lib.js:15144 Uncaught TypeError: Cannot read property 'classes' of undefined
    at factory (http://0.0.0.0:5000/static/lib/js/lib.js:15144:32)
    at http://0.0.0.0:5000/static/lib/js/lib.js:15291:9
    at Object.67.datatables (http://0.0.0.0:5000/static/lib/js/lib.js:15299:3)
    at s (http://0.0.0.0:5000/static/lib/js/lib.js:1:254)
    at http://0.0.0.0:5000/static/lib/js/lib.js:1:305
    at eval (eval at evaluate (:117:21), <anonymous>:1:1)
    at Object.<anonymous> (http://0.0.0.0:5000/static/lib/js/lib.js:829:1)
    at Object.5.datatables-bootstrap3-plugin (http://0.0.0.0:5000/static/lib/js/lib.js:951:4)
    at s (http://0.0.0.0:5000/static/lib/js/lib.js:1:254)
    at e (http://0.0.0.0:5000/static/lib/js/lib.js:1:425)
```

**Comment by jelly** [comment]
Thanks fixed the issue!
