### ISSUE TITLE
PDF generation is broken in Python 3

### ISSUE THREAD

**Issue by jelly** [der-michik/c3bottles#57]
Browsing to /label/all.pdf is broken for Python3. The StringIO module in Python 3 is now inside the "io" module. Changing the import won't help much since PIL's Image will expect BytesIO instead of StringIO. So fixing this isn't really trivial.

```
127.0.0.1 - - [08/Jan/2017 18:49:01] "GET /label/all.pdf HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jelle/projects/c3bottles/view/main.py", line 80, in dp_all_labels
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by der-michik** [comment]
I thought that would be a trivial fix, but actually, there seem to be multiple issues at once due to the strange differences in string and byte IO handling between Python 2 and 3.

Generating single PDFs looked easy. In `_pdf()` I could just do something like this:
```
try:
    from StringIO import StringIO as IO
except ImportError:
    from io import BytesIO as IO
```
This works fine in Python 2 and most of the time in Python 3 but sometimes, the Base 64 encoding fails for some strange reason in Python 3.

The fix for `dp_all_labels()` is less trivial, even more so when trying to keep the code Python 2 and 3 compatible... :(
